"""restore_is_completed_column

Revision ID: c13f2649ee25
Revises: 1036805fd646
Create Date: 2026-01-20 20:26:52.863829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c13f2649ee25'
down_revision: Union[str, Sequence[str], None] = '1036805fd646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_completed', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_completed')
    # ### end Alembic commands ###
